server:
  port: ${PORT}
spring:
  application:
    name: ${APP_NAME}
  devtools:
    add-properties: false
  profiles:
    include: ${PROFILE}
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
