server:
  port: ${PORT}
spring:
  application:
    name: ${APP_NAME}
  devtools:
    add-properties: false
  profiles:
    active: ${PROFILE}
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
