version: "3.9"

services:
  db:
    image: postgres:15
    container_name: franchise_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: franchise_db
      POSTGRES_USER: franchise_user
      POSTGRES_PASSWORD: franchise_password
      TZ: America/Bogota
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U franchise_user -d franchise_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
